version: '3'
services:
  jupyterlab:
    image: "kidig/rpi-jupyter-lab"
    ports:
      - 8888:8888
    volumes:
      - ../:/notebooks
    entrypoint: jupyter lab --no-browser --port 8888 --ip=0.0.0.0 --allow-root --NotebookApp.password='sha1:daba2b026696:b3fb474af010622c27f90aee5420698295d1260d'

