version: '3'
services:
  flask-app:
    build: ./flask-app
    restart: 'always'
    cap_add:
      - SYS_RAWIO #GPIO
    devices:
      - '/dev/mem:/dev/mem'
  rf24:
    build: ./rf24
    restart: 'always'
    cap_add:
      - SYS_RAWIO #GPIO
    devices:
      - '/dev/mem:/dev/mem'
  openhab:
    image: "openhab/openhab:2.4.0"
    restart: always
    network_mode: host
    ports:
      - 8080:8080
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./openhab/conf:/openhab/conf
      - ./openhab/userdata:/openhab/userdata
      - ./openhab/addons:/openhab/addons
    # The command node is very important. It overrides
    # the "gosu openhab tini -s ./start.sh" command from Dockerfile and runs as root!
    command: "tini -s ./start.sh server"
  db:
    image: hypriot/rpi-mysql
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
  redis:
    image: redis
  jupyterlab:
    image: "kidig/rpi-jupyter-lab"
    ports:
      - 8888:8888
    volumes:
      - ../:/notebooks
    entrypoint: jupyter lab --no-browser --port 8888 --ip=0.0.0.0 --allow-root --NotebookApp.password='sha1:daba2b026696:b3fb474af010622c27f90aee5420698295d1260d'

volumes:
  db_data:
