homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 44.7983
  longitude: -93.1529
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 246
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Show the introduction message on startup.
introduction:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Sensors
sensor:
  - platform: rest
    resource: http://flask-app:5555/test/rump
    name: Office Temperature
    value_template: '{{ value_json.state }}'
    unit_of_measurement: "°C"

  - platform: rest
    name: garage_door_sensors
    resource: http://10.0.1.3:5555/doors
    json_attributes:
      - garage_door_1
      - garage_door_2
      - garage_door_3
    value_template: 'OK'
    
  - platform: template
    sensors:
      garage_door_1:
        value_template: '{{ states.sensor.garage_door_sensors.attributes["garage_door_1"]["state"] }}'
      garage_door_2:
        value_template: '{{ states.sensor.garage_door_sensors.attributes["garage_door_2"]["state"] }}'
      garage_door_3:
        value_template: '{{ states.sensor.garage_door_sensors.attributes["garage_door_3"]["state"] }}'


# Text to speech
tts:
  - platform: google

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

nest:
  client_id: f35381c4-65fd-4daa-8795-8e24fc7b2415
  client_secret: a2RUCtHs8sGguvVMb5u0xcEsk
