
# Use this file to store secrets like usernames and passwords.
# Learn more at https://home-assistant.io/docs/configuration/secrets/
nest_client_id: [nest_client_id]
nest_client_secret: [nest_client_secret]
